### ISSUE TITLE
XCode 12 & Swift 5.3 compiler

### ISSUE THREAD

**Issue by DrikABrak** [marmelroy/Zip#199] opened 2020-09-17 12:27 UTC
Hi,

Is there possible to update Zip for Swift 5.3 compiler?
Or can someone can help me to fix this issue?
I use Zip with Carthage

Thanks a lot.

**Comment by vsgopinath** [comment] 2020-09-21 08:52
Hello @marmelroy,
         Do you have any updates on this issue. We are also facing this problem in our project.

Thanks in advance,
Gopi

**Comment by marmelroy** [comment] 2020-09-21 08:57
Hey both, I'm in the process of updating my open source frameworks for Swift 5.3 and Xcode 12. PhoneNumberKit was yesterday - will update Zip today.

**Comment by DrikABrak** [comment] 2020-09-21 10:14
Great! 

Thanks a lot!

**Comment by dornaCp** [comment] 2020-09-23 16:20
Hi,
Any update on this one?

Thanks!

**Comment by pjcau** [comment] 2020-09-25 11:43
Hi, 

I have the same issue, that I resolved in my framework that use a lipo.

So the issue is 
`/usr/bin/xcrun lipo -create /Users/jonny.cau/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/Zip/2.1.0/Build/Intermediates.noindex/ArchiveIntermediates/Zip/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Zip.framework/Zip /Users/jonny.cau/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/Zip/2.1.0/Build/Products/Release-iphonesimulator/Zip.framework/Zip -output /Users/jonny.cau/Documents/DOCOMO/work/DDHouseKit/Carthage/Build/iOS/Zip.framework/Zip`

Becasue in iOS14 now the simulator have this archs arm64 and it's a problem when try to merge with lipo create. 

So I use in the target Built Settings->Architectures-> EXCLUDED_ARCHS ->ios simulator arm64 only in release

So if you can do the same, it's build on Carthage

**Comment by marmelroy** [comment] 2020-09-26 13:30
@pjcau - this seems to be a common issue with Carthage and Xcode 12 support. Doesn't seem to be specific to Zip.

See here: https://medium.com/@quentinfasquel/carthage-issues-xcode-12-xcframeworks-apple-silicon-etc-1c60d8635dbc

**Closed by marmelroy** 2020-09-26 13:30 UTC

**Comment by pjcau** [comment] 2020-09-26 15:23
Yes, after some workaround I use a temp xcconfig to exclude from simulator archs the amr64.

Inviato da iPhone
