### ISSUE TITLE
Failed to set permissions to file

### ISSUE THREAD

**Issue by therabbitwindfall** [marmelroy/Zip#74] opened 2017-02-17 22:37 UTC
Updated my pet-project to Swift 3.0 and unzipping is totally broken. I download ZIP from my https and store into Documents. Than I unzip it in same path.

But receive error:
Failed to set permissions to file.

When I commented **Set file permissions from current fileInfo** block everything works well.

iOS Simulator 10. Not tested on real device.

Thanks.

**Comment by mostafaberg** [comment] 2017-02-18 13:47
This isn't breaking, it's just a warning, your process should work as expected, can you point out some more details or a code snippet ?

As you see [here](https://github.com/marmelroy/Zip/blob/master/Zip/Zip.swift#L202-L203) this message is only shown when setting permissions fails, files should be there and error is caught

**Comment by therabbitwindfall** [comment] 2017-02-18 14:45
Will post sample at the evening. This is not the warning. It remove owner from files and folders and lock it finally so you can't read, write as you don't owner of it anymore

Суббота, 18 февраля 2017, 16:47 +03:00 от Mostafa Torbjørn Berg <notifications@github.com>:
>This isn't breaking, it's just a warning, your process should work as expected, can you point out some more details or a code snippet ?
>As you see  here this message is only shown when setting permissions fails, files should be there and error is caught
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


skype: therabbitwindfall

**Comment by therabbitwindfall** [comment] 2017-02-18 20:27
Ok, here is image what I have. After file was downloaded from https and placed into Documents folder on iOS Simulator - ZIP extracting is started.

I see errors in console that **Failed to set permissions to file**. Please note that Zip was produced by WinRar on Windows 10, uploaded to ngnix as binary zip and downloaded into iOS.

Zip doesn't include any owner info because WinRar and 7zip for Windows don't put any Userinfo for permissions. Looks like it works fine with zips created on OSX but not on Windows.

On my image you can see that after extracting Zip file - it create folder (it's ok, Zip include this folder).
Next step - it's extracting files. But files can't be extracted because folder have wrong Permissions "everyone" and "no access".

My idea is that Permission setting totally broken and should be removed...

Can't send my project at this moment. But commenting Zip.swift file where is about Permission from fileinfo - it works well :)

![2017-02-16_170301](https://cloud.githubusercontent.com/assets/1976931/23096600/efeb4606-f630-11e6-9b79-0ccf0ace93e6.jpg)

**Comment by mostafaberg** [comment] 2017-02-18 20:47
Ok that is a very interesting issue, i guess for a quick workaround just use a zip applications that stores permission info, Or even better use the version before the current one in your podfile to avoid using the feature completely, I did that permissions feature due to an issue by a user that requested it and it made sense to implement. seems like the tests werent thorough enough. I would say its up to @marmelroy to keep the permissions feature or remove it, Zip by default doesnt really care about permissions so its not a huge harm to remove the feature. it's a "nice to have" per se. lets see after the weekend :) i might just implement a default permissions as a fallback , what do you think @marmelroy?

**Comment by mostafaberg** [comment] 2017-02-20 08:45
I did a quick test right now and unzipping a zip file made on WinRAR for windows seems to work ok, can you supply an example file that's causing this issue for you ?

**Comment by mostafaberg** [comment] 2017-02-22 09:28
@therabbitwindfall I'm still waiting for a test zip file, it will help a lot with speeding up the process, let me know whenever you have a moment to send me a test archive that reproduces the issue

**Comment by classified** [comment] 2017-02-27 12:14
Well, i've tested this problem with **cocoa pods version 0.6** . There are no issues so far. Like ex. if i give a file only read permission and archive it, after unarchive with Zip then that file contains same permission as it did before getting zipped.

But when i use **master branch source with pods** for the same scenario, then it will set permission on file with **No Access for everyone.**

Please find below attachment. i've used this zip for both scenario.

[D1DF97FC-8C7A-4CA5-9EAB-14CA1A7BCA11.zip](https://github.com/marmelroy/Zip/files/803580/D1DF97FC-8C7A-4CA5-9EAB-14CA1A7BCA11.zip)

**Comment by mostafaberg** [comment] 2017-02-27 12:35
Zipinfo on your zip file shows that

```
Zip file size: 3244 bytes, number of entries: 2
-rw----     0.0 fat     6148 b- defN 17-Feb-27 12:30 Documents/.DS_Store
-rw----     0.0 fat    90112 b- defN 17-Feb-27 12:19 Documents/GamestateDB.sqlite
2 files, 96260 bytes uncompressed, 2976 bytes compressed:  96.9%
```

I'll make a change to bypass permissions if they are not set in the fileinfo, this should fix it for you while maintaining the feature to other users who require permissions

**Comment by mostafaberg** [comment] 2017-02-27 13:13
Coming with a fix soon, tested the the default behavior on macOS and iOS and they both set the permission to `-rw-r--r-- (644)` when there is no file info set, doing the same behaviour here

Basically the library will follow this flow:

- Read permission flags from file info property
    - Permissions not found:
        - Set default `644`
    - Permissions found:
        - Convert to unix permissions
            - if it fits between `400` and `777`, this value will be set
            - if it doesn't fit, default is set`644`

This should fix your problem and will preserve the permissions feature for supported archives.

**Comment by mostafaberg** [comment] 2017-02-27 13:26
@classified Thanks for your help, the [PR](https://github.com/marmelroy/Zip/pull/75) is out now and @marmelroy can take a look and decide what to do next.

**Comment by therabbitwindfall** [comment] 2017-02-27 14:34
Thanks a lot for support! Just back to my desktop and that I'm not alone with this so my help not needed ;)

**Comment by JackoPlane** [comment] 2017-03-14 08:31
Any update on this as I too am suffering the above issue.

**Comment by mostafaberg** [comment] 2017-03-14 08:51
I have a fix branch out there that you can set in your Podfile instead of using the version 0.6 tag, until it's merged

https://github.com/marmelroy/Zip/tree/bugfix/issue74

**Closed** 2017-03-20 08:12 UTC
